browserbase/stagehand-python

stagehand/page.py

unpack the input options as the base playwright `screenshot` method accepts keyword arguments only
can't use the `screenshot` function bc of this bug when on local env
simple unpacking for arguments to comply to base playwright `screenshot` method that accepts keyword arguments only
https://github.com/microsoft/playwright-python/blob/0ff7fc983ef39ed6121ffbac4eaf15e9b02a6aba/playwright/async_api/_generated.py#L2768
regular (?)

(very) simple bug fix for screenshot method

---

.github/workflows/publish.yml

temporarily comment pytests on publish workflow

---

stagehand/config.py
stagehand/main.py

The default api url always override the one specified in .env
fixed init and config to prioritize the .env `STAGEHAND_API_URL`

fix bug on api_url load from .env

---

README.md

config `model_client_options` is not in config.py, this configuration not working
https://github.com/browserbase/stagehand-python/blob/main/stagehand/config.py#L22
change this config to model_api_key

fix api key example in README

---

stagehand/browser.py

To unblock certain local configurations
added optional headers to be passed on cdp_url if local_browser_launch_options includes the 'headers' key

add headers to cdp connect (#136)

---

.changeset/belligerent-gharial-of-attack.md
stagehand/api.py

To help debug sessions faster and to respect backwards version compatibility long term

pass sdk version number to api for debug

---

.changeset/wakeful-pogona-of-stamina.md
.changeset/wealthy-lion-of-honeydew.md
stagehand/main.py
tests/unit/test_client_initialization.py

Strict event loop envs break due to blocking behavior inside async playwright start.

add timeout to async playwright

---

stagehand/handlers/act_handler_utils.py

Resolves this issue:
https://github.com/browserbase/stagehand-python/issues/154
Use the proper `Locator.press` method to in the `press_key` util function.
The existing `test_keyboard_actions_local` touches this and now works without any errors.
I fixed the log lower down that would throw the same exception.

Fix error in press_key act util function

---

.changeset/sceptical-mutant-shrew.md
stagehand/handlers/act_handler_utils.py

Keypress actions in `MethodHandlerContext` are not set up properly
Updated the keypresses to use keyboard events on `MethodHandlerContext`

Fix error in press_key act util function (#155)

---

.changeset/masterful-amiable-leopard.md
stagehand/agent/agent.py
stagehand/agent/anthropic_cua.py
stagehand/agent/image_compression_utils.py

why
part of STG-586
Currently, we leave all of the images for anthropic cua client within the LLM's context as the task progresses
what changed
We now remove all screenshots aside from the last two when experimental flag is set to true within stagehand config
test plan
tested locally

remove all images except the latest two in AnthropicCuaClient

---

.changeset/daffy-rapid-turaco.md
format
stagehand/handlers/extract_handler.py
stagehand/page.py
stagehand/types/__init__.py
stagehand/types/page.py

The full page extract schema differs on `env:"LOCAL"` and `env:"BROWSERBASE"`
Standardized the `EmptyExtractSchema` for both environments

Fix parsing schema for extract with no arguments

---

.changeset/woodoo-frog-of-growth.md
stagehand/page.py

fix logging

---

.changeset/warping-colorful-shellfish.md
stagehand/api.py
stagehand/main.py

Session id is not serialized properly when reconnecting to a session
Made sure `init()` calls `_createSession()` when passing an existing session_id

Patch issue with passing a created session_id to init on api mode

---

.changeset/ambrosial-anaconda-of-blizzard.md
stagehand/page.py
stagehand/schemas.py

The new version of Stagehand API supports iframes, but the python sdk doesn't directly support them
Enabled access to setting `iframes:True` whenever the environment is "BROWSERBASE" (with api enabled)

Enable access to iframes on api

---

.changeset/vegan-intrepid-mustang.md
stagehand/context.py
stagehand/page.py
tests/integration/api/test_frame_id_integration.py
tests/unit/core/test_frame_id_tracking.py

Feature parity for PRs in [TS](https://github.com/browserbase/stagehand):
- [#907](https://github.com/browserbase/stagehand/pull/907)
- [#920](https://github.com/browserbase/stagehand/pull/920)
Stagehand now provides multi-tab support and this PR allows consistent expected behavior on both envs ("BROWSERBASE/LOCAL")
- Added a `frame_id_map` to keep track of pages (now that live_page_proxy auto updates) in `context.py`
- Added a `frame_id` property to `StagehandPage`
- Pass the optional `frame_id` on api routes
Included unit test and regression:

Frame ID map for multi-tab support (API)

---

.changeset/towering-organic-grouse.md
stagehand/llm/client.py

OpenAI decided to change their inference configuration
New GPT-5 family models don't accept temperature as an option, set `temperature:1` for this family of models

Fix temp setting for GPT-5

---

.changeset/inventive-tangible-hyena.md
stagehand/config.py
tests/integration/local/test_core_local.py

Copying from Derek's branch: https://github.com/browserbase/stagehand-python/pull/170
if you add custom browserbase create params, you need to include the project id even if the project id is already passed to the stagehand instance
relaxed browserbase params definition and added a field validator to add project id from the stagehand config before validating structure
ran tests with shell command

remove need for project id in Browserbase params if already passed to stagehand

---

.changeset/outrageous-adept-hyena.md
stagehand/handlers/observe_handler.py
stagehand/utils.py

Fixes an error with draw_overlay on elements
Loads elements into a list[dict] with `modelDump()` from the observeResult Pydantic objects

Dump ObserveResult to dict before passing to draw_overlay (#198)

---

.changeset/literate-dancing-tuatara.md
pyproject.toml

Openai version is quite outdated
Bumped `openai` version on `pyproject.toml` to `>=1.99.6`

bump openai version

---

.changeset/horned-giga-cockatoo.md
examples/agent_example.py
pyproject.toml
stagehand/agent/agent.py
stagehand/agent/anthropic_cua.py
stagehand/agent/google_cua.py
stagehand/agent/openai_cua.py
stagehand/browser.py
stagehand/schemas.py

Adding support for Gemini's new Computer Use model
We partnered with Google Deepmind to help integrate and test their new Computer Use models. 
The new model tag `gemini-2.5-pro-computer-use-preview-10-2025` is available for Stagehand Agent. You can try it today with the example `agent-example.py`
To learn more, check out the blog post [https://www.browserbase.com/blog/evaluating-browser-agents](https://www.browserbase.com/blog/evaluating-browser-agents)

Support for new Gemini Computer Use Models
